name: hassfest

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    name: hassfest
    runs-on: "ubuntu-latest"
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v7
      - uses: home-assistant/actions/hassfest@master
